---
abstract: 'transparent telnet negotiation for IO::Socket::INET'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.89'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Socket-Telnet
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
