--- 
abstract: transparent telnet negotiation for IO::Socket::INET
author: Shawn M Moore, C<< <sartak at gmail.com> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: IO-Socket-Telnet
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Method::Modifiers: 0
  IO::Socket::INET: 0
  parent: 0
version: 0.02
